import React, { useState, useEffect } from 'react';
import DashboardLayout from '@/app/layout/DashboardLayout';
import { ChatMessage } from './AI/types';
import AIHeader from './AI/AIHeader';
import PricingBanner from './AI/PricingBanner';
import AIStats from './AI/AIStats';
import ChatInterface from './AI/ChatInterface';
import SessionStats from './AI/SessionStats';
import UsageHistory from './AI/UsageHistory';
import Analytics from './AI/Analytics';
import CostBreakdown from './AI/CostBreakdown';

const AI: React.FC = () => {
  const [balance] = useState(0);
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [session, setSession] = useState({
    id: 'session-1',
    sessionNumber: 1,
    startTime: new Date().toLocaleString(),
    calls: 0,
    cost: 0,
    topics: [],
    messages: [],
  });

  // Scroll to top on component mount
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  const handleSendMessage = (content: string) => {
    if (balance < 0.001) return;

    // Add user message
    const userMessage: ChatMessage = {
      id: `user-${Date.now()}`,
      role: 'user',
      content,
      timestamp: 'Just now',
    };

    // Add AI response (simulated)
    const aiMessage: ChatMessage = {
      id: `ai-${Date.now()}`,
      role: 'assistant',
      content: 'This is a simulated AI response. In a real application, this would be generated by an AI service.',
      timestamp: 'Just now',
      cost: 0.001,
    };

    setMessages([...messages, userMessage, aiMessage]);
    
    // Update session
    setSession({
      ...session,
      calls: session.calls + 1,
      cost: session.cost + 0.001,
    });
  };

  const handleNewSession = () => {
    setMessages([]);
    setSession({
      ...session,
      sessionNumber: session.sessionNumber + 1,
      calls: 0,
      cost: 0,
      topics: [],
      messages: [],
    });
  };

  const handleExportChat = () => {
    const chatData = {
      session: session,
      messages: messages,
      exportedAt: new Date().toISOString(),
    };
    const blob = new Blob([JSON.stringify(chatData, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `chat-session-${session.sessionNumber}.json`;
    a.click();
  };

  const handleClearChat = () => {
    setMessages([]);
  };

  const handleSaveConversation = () => {
    // In a real app, this would save to backend
    console.log('Saving conversation...', { session, messages });
  };

  const handleDeposit = () => {
    // In a real app, this would open deposit modal
    console.log('Opening deposit modal...');
  };

  return (
    <DashboardLayout>
      <AIHeader />
      {/* <PricingBanner balance={balance} /> */}
      <AIStats
        totalSpent={0}
        totalCalls={0}
        avgPerCall={0}
        thisMonth={0}
      />
      
      <div className="grid grid-cols-1 xl:grid-cols-10 gap-6 mb-8">
        <div className="xl:col-span-7">
          <ChatInterface
            messages={messages}
            onSendMessage={handleSendMessage}
            balance={balance}
            suggestedPrompts={[]}
          />
        </div>
        <div className="xl:col-span-3">
          <SessionStats
            session={session}
            balance={balance}
            onNewSession={handleNewSession}
            onExportChat={handleExportChat}
            onClearChat={handleClearChat}
            onSaveConversation={handleSaveConversation}
            onDeposit={handleDeposit}
          />
        </div>
      </div>

      <UsageHistory history={[]} />
      <Analytics callsData={[]} topicData={[]} />
      {/* <CostBreakdown data={costBreakdown} /> */}
    </DashboardLayout>
  );
};

export default AI;
