import { Video, OwnedVideo, UsageHistoryItem, AnalyticsData } from './types';

export const availableVideos: Video[] = [
  {
    id: 'nTbA7qrEsP0',
    title: 'Video 1',
    duration: '10:00',
    quality: '1080p',
    thumbnail: 'https://img.youtube.com/vi/nTbA7qrEsP0/hqdefault.jpg',
    streamPrice: 0.0001,
    purchasePrice: 0.06,
    description: 'Available for streaming or purchase',
  },
  {
    id: 'RVm2Debv_Ic',
    title: 'Video 2',
    duration: '15:30',
    quality: '1080p',
    thumbnail: 'https://img.youtube.com/vi/RVm2Debv_Ic/hqdefault.jpg',
    streamPrice: 0.0001,
    purchasePrice: 0.09,
    description: 'Available for streaming or purchase',
  },
  {
    id: 'IE5H0lMLUw8',
    title: 'Video 3',
    duration: '20:00',
    quality: '4K',
    thumbnail: 'https://img.youtube.com/vi/IE5H0lMLUw8/hqdefault.jpg',
    streamPrice: 0.0001,
    purchasePrice: 0.12,
    description: 'Available for streaming or purchase',
  },
  {
    id: '1__SDbGPUQM',
    title: 'Video 4',
    duration: '12:45',
    quality: '1080p',
    thumbnail: 'https://img.youtube.com/vi/1__SDbGPUQM/hqdefault.jpg',
    streamPrice: 0.0001,
    purchasePrice: 0.075,
    description: 'Available for streaming or purchase',
  },
];

export const ownedVideos: OwnedVideo[] = [
  {
    id: 'k18gSPjWDM0',
    title: 'Library Video 1',
    duration: '10:00',
    quality: '1080p',
    thumbnail: 'https://img.youtube.com/vi/k18gSPjWDM0/hqdefault.jpg',
    streamPrice: 0.0001,
    purchasePrice: 0.09,
    watchCount: 12,
    lastWatched: '2 hours ago',
  },
  {
    id: 'yKbkQ6Vndss',
    title: 'Library Video 2',
    duration: '15:30',
    quality: '1080p',
    thumbnail: 'https://img.youtube.com/vi/yKbkQ6Vndss/hqdefault.jpg',
    streamPrice: 0.0001,
    purchasePrice: 0.12,
    watchCount: 5,
    lastWatched: '1 day ago',
  },
  {
    id: 'c1rBk7XAlj0',
    title: 'Library Video 3',
    duration: '20:00',
    quality: '4K',
    thumbnail: 'https://img.youtube.com/vi/c1rBk7XAlj0/hqdefault.jpg',
    streamPrice: 0.0001,
    purchasePrice: 0.075,
    watchCount: 8,
    lastWatched: '3 days ago',
  },
  {
    id: 'SZywj7k6tBI',
    title: 'Library Video 4',
    duration: '12:45',
    quality: '1080p',
    thumbnail: 'https://img.youtube.com/vi/SZywj7k6tBI/hqdefault.jpg',
    streamPrice: 0.0001,
    purchasePrice: 0.11,
    watchCount: 5,
    lastWatched: '5 days ago',
  },
  {
    id: 'fKoHcAM0PEk',
    title: 'Library Video 5',
    duration: '18:20',
    quality: '1080p',
    thumbnail: 'https://img.youtube.com/vi/fKoHcAM0PEk/hqdefault.jpg',
    streamPrice: 0.0001,
    purchasePrice: 0.05,
    watchCount: 3,
    lastWatched: '1 week ago',
  },
  {
    id: 'flxZd7EFhSo',
    title: 'Library Video 6',
    duration: '8:30',
    quality: '720p',
    thumbnail: 'https://img.youtube.com/vi/flxZd7EFhSo/hqdefault.jpg',
    streamPrice: 0.0001,
    purchasePrice: 0.05,
    watchCount: 2,
    lastWatched: '2 weeks ago',
  },
];

export const usageHistory: UsageHistoryItem[] = [
  {
    id: '1',
    type: 'stream',
    videoTitle: 'Introduction to StreamPay',
    date: '2 hours ago',
    duration: '00:42:15',
    cost: 0.0425,
  },
  {
    id: '2',
    type: 'purchase',
    videoTitle: 'Advanced Payment Streaming',
    date: '5 hours ago',
    cost: 0.09,
  },
  {
    id: '3',
    type: 'stream',
    videoTitle: 'Introduction to StreamPay',
    date: '1 day ago',
    duration: '00:31:12',
    cost: 0.0312,
  },
  {
    id: '4',
    type: 'purchase',
    videoTitle: 'Smart Contract Integration',
    date: '2 days ago',
    cost: 0.12,
  },
  {
    id: '5',
    type: 'purchase',
    videoTitle: 'API Best Practices',
    date: '3 days ago',
    cost: 0.075,
  },
  {
    id: '6',
    type: 'stream',
    videoTitle: 'Security & Privacy',
    date: '4 days ago',
    duration: '00:25:30',
    cost: 0.0253,
  },
  {
    id: '7',
    type: 'purchase',
    videoTitle: 'Getting Started Guide',
    date: '1 week ago',
    cost: 0.05,
  },
];

export const analyticsData: AnalyticsData[] = [
  { date: 'Nov 1', streamingCost: 0.1, purchaseCost: 0 },
  { date: 'Nov 5', streamingCost: 0.3, purchaseCost: 0.09 },
  { date: 'Nov 10', streamingCost: 0.2, purchaseCost: 0.12 },
  { date: 'Nov 15', streamingCost: 0.4, purchaseCost: 0.075 },
  { date: 'Nov 20', streamingCost: 0.3, purchaseCost: 0.05 },
  { date: 'Nov 25', streamingCost: 0.5, purchaseCost: 0 },
  { date: 'Nov 27', streamingCost: 0.42, purchaseCost: 0 },
];

export const videoStats = {
  totalSpent: 4.45,
  videosOwned: 4, // Updated to match ownedVideos length
  totalWatched: 12.5,
  sessions: 47,
};

