import { Video, OwnedVideo, UsageHistoryItem, AnalyticsData } from './types';

export const availableVideos: Video[] = [
  {
    id: '1',
    title: 'Introduction to StreamPay',
    duration: '10:00',
    quality: '1080p',
    thumbnail: 'https://via.placeholder.com/300x200?text=Video+1',
    streamPrice: 0.0001,
    purchasePrice: 0.06,
    description: 'Learn the basics of StreamPay and how it works',
  },
  {
    id: '2',
    title: 'Advanced Payment Streaming',
    duration: '15:30',
    quality: '1080p',
    thumbnail: 'https://via.placeholder.com/300x200?text=Video+2',
    streamPrice: 0.0001,
    purchasePrice: 0.09,
    description: 'Deep dive into advanced streaming features',
  },
  {
    id: '3',
    title: 'Smart Contract Integration',
    duration: '20:00',
    quality: '4K',
    thumbnail: 'https://via.placeholder.com/300x200?text=Video+3',
    streamPrice: 0.0001,
    purchasePrice: 0.12,
    description: 'How to integrate StreamPay with smart contracts',
  },
  {
    id: '4',
    title: 'API Best Practices',
    duration: '12:45',
    quality: '1080p',
    thumbnail: 'https://via.placeholder.com/300x200?text=Video+4',
    streamPrice: 0.0001,
    purchasePrice: 0.075,
    description: 'Best practices for using the StreamPay API',
  },
  {
    id: '5',
    title: 'Security & Privacy',
    duration: '18:20',
    quality: '1080p',
    thumbnail: 'https://via.placeholder.com/300x200?text=Video+5',
    streamPrice: 0.0001,
    purchasePrice: 0.11,
    description: 'Security measures and privacy considerations',
  },
  {
    id: '6',
    title: 'Getting Started Guide',
    duration: '8:30',
    quality: '720p',
    thumbnail: 'https://via.placeholder.com/300x200?text=Video+6',
    streamPrice: 0.0001,
    purchasePrice: 0.05,
    description: 'Quick start guide for new users',
  },
];

export const ownedVideos: OwnedVideo[] = [
  {
    id: '2',
    title: 'Advanced Payment Streaming',
    duration: '15:30',
    quality: '1080p',
    thumbnail: 'https://via.placeholder.com/300x200?text=Video+2',
    streamPrice: 0.0001,
    purchasePrice: 0.09,
    watchCount: 12,
    lastWatched: '2 hours ago',
  },
  {
    id: '3',
    title: 'Smart Contract Integration',
    duration: '20:00',
    quality: '4K',
    thumbnail: 'https://via.placeholder.com/300x200?text=Video+3',
    streamPrice: 0.0001,
    purchasePrice: 0.12,
    watchCount: 5,
    lastWatched: '1 day ago',
  },
  {
    id: '4',
    title: 'API Best Practices',
    duration: '12:45',
    quality: '1080p',
    thumbnail: 'https://via.placeholder.com/300x200?text=Video+4',
    streamPrice: 0.0001,
    purchasePrice: 0.075,
    watchCount: 8,
    lastWatched: '3 days ago',
  },
  {
    id: '6',
    title: 'Getting Started Guide',
    duration: '8:30',
    quality: '720p',
    thumbnail: 'https://via.placeholder.com/300x200?text=Video+6',
    streamPrice: 0.0001,
    purchasePrice: 0.05,
    watchCount: 3,
    lastWatched: '1 week ago',
  },
];

export const usageHistory: UsageHistoryItem[] = [
  {
    id: '1',
    type: 'stream',
    videoTitle: 'Introduction to StreamPay',
    date: '2 hours ago',
    duration: '00:42:15',
    cost: 0.0425,
  },
  {
    id: '2',
    type: 'purchase',
    videoTitle: 'Advanced Payment Streaming',
    date: '5 hours ago',
    cost: 0.09,
  },
  {
    id: '3',
    type: 'stream',
    videoTitle: 'Introduction to StreamPay',
    date: '1 day ago',
    duration: '00:31:12',
    cost: 0.0312,
  },
  {
    id: '4',
    type: 'purchase',
    videoTitle: 'Smart Contract Integration',
    date: '2 days ago',
    cost: 0.12,
  },
  {
    id: '5',
    type: 'purchase',
    videoTitle: 'API Best Practices',
    date: '3 days ago',
    cost: 0.075,
  },
  {
    id: '6',
    type: 'stream',
    videoTitle: 'Security & Privacy',
    date: '4 days ago',
    duration: '00:25:30',
    cost: 0.0253,
  },
  {
    id: '7',
    type: 'purchase',
    videoTitle: 'Getting Started Guide',
    date: '1 week ago',
    cost: 0.05,
  },
];

export const analyticsData: AnalyticsData[] = [
  { date: 'Nov 1', streamingCost: 0.1, purchaseCost: 0 },
  { date: 'Nov 5', streamingCost: 0.3, purchaseCost: 0.09 },
  { date: 'Nov 10', streamingCost: 0.2, purchaseCost: 0.12 },
  { date: 'Nov 15', streamingCost: 0.4, purchaseCost: 0.075 },
  { date: 'Nov 20', streamingCost: 0.3, purchaseCost: 0.05 },
  { date: 'Nov 25', streamingCost: 0.5, purchaseCost: 0 },
  { date: 'Nov 27', streamingCost: 0.42, purchaseCost: 0 },
];

export const videoStats = {
  totalSpent: 4.45,
  videosOwned: 4, // Updated to match ownedVideos length
  totalWatched: 12.5,
  sessions: 47,
};

